name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'DCE/**'
      - 'res/**'
      - 'Dockerfile'
      - 'requirements.txt'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: socrates-backend
          region: europe-southwest1
          source: ./
